### ISSUE TITLE
space between words

### ISSUE THREAD

**Issue by ufukayyildiz** [anurag-roy/og.anuragroy.dev#1]
hi,

thanks for this great app.

if meta description is more then one word, example: test test2 test3, facebook does not fetch the image.

linkedin does.

But if added %20 between work it works.

So how can i add %20 between words for both title and description words?

thank you.

**Comment by anurag-roy** [comment]
@ufukayyildiz I'm not sure I understand.

So, for a `title` "Title" and `description` "test1 test2", this is the current generated URL: https://og.anuragroy.dev/api?theme=rose&title=title&description=test1+test2.

The above does not work on Facebook but instead this one does: https://og.anuragroy.dev/api?theme=rose&title=title&description=test1%20test2&logo=%F0%9F%90%A6 ?

**Comment by ufukayyildiz** [comment]
sorry :( , it is related where i used this code.
