### ISSUE TITLE
Instructions to use this repo

### ISSUE THREAD

**Issue by techieforgood** [anurag-roy/og.anuragroy.dev#2]
Hi @anurag-roy, thanks for creating this OG service.

I'm unfamiliar with NextJS development and deployment. If you can include some documentation in your readme regarding how to setup this project, it will be great.

Basically I am looking for :

- steps after I clone your repository
- what are the prerequisites?
- what commands do I have to run?
- how do I preview locally?
- how do I deploy it to Vercel (is it just connecting my repo or do I need to set some environment variables or any other steps?).

To simplify your job, I have created a draft below, which you can use if you wish.
Tip: you can click on  the three dots -> Edit -> Select all the Markdown content -> Copy it. Now you can simply paste this in the readme to get started. Hope this will save you some time.

**Comment by techieforgood** [comment]
## How to use

### Prerequisites
Ensure that you have Node>X.Y.Z, npm or pnpm.

### Steps
1. Clone the repo

    ```
    https://github.com/anurag-roy/og.anuragroy.dev
    ```

2. Install dependencies
    ```
    npm install
    ```
3. Local development
Run `npm run dev` to preview the service locally. You can customize the look and feel of the OG image at `pages/api/index.tsx`. Here you can set the defaults (domain name, avatar, font used etc.).
4. Deployment
After making necessary changes, push your repo to GitHub/GitLab and connect it to Vercel. Then set the following environment variables: (if any).

**Comment by anurag-roy** [comment]
@techieforgood Thanks for raising this.

I'll add instructions on how to use this and maybe refactor slightly to make it a little easier to clone/deploy for others. Will keep you updated.

**Comment by techieforgood** [comment]
> I'll add instructions on how to use this and maybe refactor slightly to make it a little easier to clone/deploy for others.

That will be great @anurag-roy.

**Comment by anurag-roy** [comment]
@techieforgood I've added some usage instructions, lmk what you think!

**Comment by techieforgood** [comment]
Thanks @anurag-roy for adding a detailed documentation. It is surely more than what I expected.
